name: MLflow Project Retrain CI

on:
  workflow_dispatch:
  push:
    paths:
      - 'MLProject/**'
      - 'MLProject/MLProject'
      - 'MLProject/modelling.py'
      - 'MLProject/conda.yaml'
      - 'MLProject/bostonhousing_preprocessing*'

jobs:
  retrain:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          environment-file: MLProject/conda.yaml
          activate-environment: mlflow-env

      - name: Install MLflow
        run: conda install -y -c conda-forge mlflow

      - name: Run MLflow Project
        run: mlflow run MLProject

      - name: Upload model artifact
        uses: actions/upload-artifact@v4
        with:
          name: trained-model-artifacts
          path: MLProject/test_data.csv

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mlflow-bostonhousing:latest MLProject

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mlflow-bostonhousing:latest
